### ISSUE TITLE
question about dataset

### ISSUE THREAD

**Issue by happyflying-web** [real-stanford/xskill#3]
Great work !
I hava a question about dataset. For example，a video at `data_v2/human_draw_cloth_light/videos/2/1/color.mp4`, the content is  as follows . Does this video have any practical significance? Or is it noisy data? Thank you！
![image](https://github.com/real-stanford/xskill/assets/58216366/8d30a8d9-671b-4895-9a67-0138d3cb71ee)

**Comment by mengdaxu** [comment]
Hi, the video you are showing is not used during training. The robot wrist mounted camera was still on during human data collection. Yes, it is just noisy data.

**Comment by happyflying-web** [comment]
Thanks for your reply！
